In [7]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [8]:
data = pd.read_csv("train.csv")

In [9]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [10]:
data = np.array(data)
row, column = data.shape # (feature + 1 --> +1 is the label column)
np.random.shuffle(data)

data_val = data[0:1000].T # transposing to make each column an example instead of each row
Y_val = data_val[0]
X_val = data_val[1:column]
X_val = X_val / 255.

data_train = data[1000:row].T
Y_train = data_train[0]
X_train = data_train[1:column]
X_train = X_train / 255.
_,m_train = X_train.shape

In [11]:
def init_params():
    # np.random.rand will generate a random values between 0 and 1 for each element of the array, subtruct 0.5 to make it zero centered
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5

    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / sum(np.exp(Z))

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0 # when booleans are converted to numbers True -> 1 False -> 0

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / row * dZ2.dot(A1.T)
    db2 = 1 / row * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / row * dZ1.dot(X.T)
    db1 = 1 / row * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate):
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    return W1, b1, W2, b2

In [12]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def calc_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 50 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print("Accuracy: ", calc_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [13]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.1)

Iteration:  0
[6 5 6 ... 1 5 0] [9 7 9 ... 7 2 5]
Accuracy:  0.09290243902439024
Iteration:  50
[9 7 6 ... 6 4 0] [9 7 9 ... 7 2 5]
Accuracy:  0.4614878048780488
Iteration:  100
[9 7 9 ... 6 6 5] [9 7 9 ... 7 2 5]
Accuracy:  0.676439024390244
Iteration:  150
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.7481463414634146
Iteration:  200
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.7832682926829269
Iteration:  250
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.8043414634146342
Iteration:  300
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.8192926829268292
Iteration:  350
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.830390243902439
Iteration:  400
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.8388048780487805
Iteration:  450
[9 7 9 ... 7 2 5] [9 7 9 ... 7 2 5]
Accuracy:  0.8455609756097561
